set -g mode-style "fg=#0c1917,bg=#e0b563"
set -g message-style "fg=#9fc9bd,bg=#142320"
set -g message-command-style "fg=#9fc9bd,bg=#142320"

set -g pane-border-style "fg=#24413c"
set -g pane-active-border-style "fg=#4fd8b0"

set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#9fc9bd,bg=#0c1917"
set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left "#[fg=#0c1917,bg=#4fd8b0,bold] #S #[fg=#4fd8b0,bg=#0c1917,nobold]"
set -g status-right "#[fg=#24413c,bg=#0c1917]#[fg=#9fc9bd,bg=#24413c] %H:%M #[fg=#4fd8b0,bg=#24413c]#[fg=#0c1917,bg=#4fd8b0,bold] %d-%b "

setw -g window-status-activity-style "fg=#e0b563,bg=#0c1917,none"
setw -g window-status-separator ""
setw -g window-status-style "fg=#46615c,bg=#0c1917,none"
setw -g window-status-format "#[fg=#0c1917,bg=#0c1917] #I #[fg=#46615c,bg=#0c1917] #W "
setw -g window-status-current-format "#[fg=#0c1917,bg=#24413c]#[fg=#4fd8b0,bg=#24413c,bold] #I #[fg=#9fc9bd,bg=#24413c] #W #[fg=#24413c,bg=#0c1917]"

set -g popup-style "fg=#9fc9bd,bg=#142320"
set -g popup-border-style "fg=#4fd8b0,bg=#142320"

set -g pane-border-status top
set -g pane-border-format "#{?#{==:#{pane_current_command},ssh},#[fg=#e0985c]● SSH #[fg=#46615c]#{pane_current_command},#[fg=#46615c]#{pane_current_command}}"
